0.1.1 19 local_data_platform.source.near.bigquery.get(query)
tusharchou/local-data-platform pull request #25
Opened 2024-10-01 16:08 UTC by mrutunjay-kinagi

2024-10-01 20:18 UTC, tusharchou approved these changes
All these comments can be addressed later LGTM 👍

2024-10-01 20:18 UTC, tusharchou commented on local-data-platform/local_data_platform/source/gcp/gcp_bigquery/source_gcp_bigquery.py
> +        self.client = GCPBigQueryConnection('path/to/credentials.json', 'your-project-id')
This looks great! 👍

2024-10-01 20:18 UTC, tusharchou commented on local-data-platform/local_data_platform/source/gcp/gcp_bigquery/source_gcp_bigquery.py
> +            pandas.DataFrame: The result of the query as a DataFrame.
Really detailed documentation

2024-10-01 20:18 UTC, tusharchou commented on local-data-platform/local_data_platform/source/gcp/gcp_connection.py
> +    def query(self, query_string):
maybe this is could be moved to big query class

2024-10-01 20:18 UTC, tusharchou commented on local-data-platform/local_data_platform/source/near/source_near_gcp.py
> +class Source_Near_GCP(SourceGCPBigQuery):
this class should have columns required we can come up with a list together

2024-10-03 12:14 UTC, mrutunjay-kinagi commented
Added pytest  files.

2024-10-04 01:42 UTC, tusharchou requested changes

2024-10-04 01:42 UTC, tusharchou commented on local-data-platform/local_data_platform/source/gcp/gcp_connection.py
> +            print(row)
Exceptional documentation!!!

2024-10-04 01:42 UTC, tusharchou commented on local-data-platform/local_data_platform/source/near/source_near_gcp.py
> +class Source_Near_GCP(SourceGCPBigQuery):
Class name can be camel case

2024-10-04 01:42 UTC, tusharchou commented on local-data-platform/local_data_platform/source/near/source_near_gcp.py
> +            FROM `bigquery-public-data.crypto_near.transactions`
Can we read the sql from a file will make it configurable

2024-10-04 01:42 UTC, tusharchou commented on local-data-platform/tests/test_gcp_connection.py
> +import pytest
This is what makes a good lib great!

2024-10-07 11:14 UTC, tusharchou approved these changes
Lets test this with a demo

2024-10-07 11:15 UTC, merged

2024-11-08 08:18 UTC, redpheonixx commented
> Added pytest files.

### pytests are failing
![image](https://github.com/user-attachments/assets/fcad7f63-062b-43a6-8abd-702bea25a3e7)

The error message indicates that Python is unable to import the `GCPBigQueryConnection` from the specified module. Here are some potential solutions:

1. **Check the Import Path**: Ensure that the path to `GCPBigQueryConnection` is correct and that it exists in `local_data_platform/store/source/gcp/bigquery/__init__.py`.
   
2. **Correct Package and Module Names**: Make sure that all package and module names are correctly spelled and follow Python naming conventions.

3. **Ensure `__init__.py` Exists**: Verify that an `__init__.py` file is present in the `local_data_platform`, `store`, `source`, `gcp`, and `bigquery` directories to make them proper Python packages.

4. **Relative Import Issues**: If you are using relative imports, ensure they are correctly specified. Sometimes converting relative imports to absolute imports can solve the issue.

5. **Check for Circular Imports**: Make sure that your code does not have circular imports, where two or more modules are trying to import each other.

Here's an example of what the `__init__.py` might look like:

```python
# local_data_platform/store/source/gcp/bigquery/__init__.py

from .bigquery import GCPBigQueryConnection
```

If all these steps are correctly followed and the issue still persists, please share more details or additional error messages for further troubleshooting. Good luck! 🚀