Updated Problem Statement and Plan
tusharchou/local-data-platform pull request #30
Opened 2024-10-03 12:08 UTC by tusharchou

Thu 3 Oct 5:34 PM 
#26 feature iceberg local table 
#25 feature big query gcp api

2024-10-03 12:17 UTC, mrutunjay-kinagi approved these changes
LGTM  🚀

2024-10-03 12:17 UTC, tusharchou commented
Need a good review

2024-10-04 02:04 UTC, Col-Rajesh-Kumar requested changes
Please provide timeline with buffer time.

2024-10-04 02:04 UTC, Col-Rajesh-Kumar commented on README.md
> +| 0.1.1     | BigQuery             | 3rd Oct 24   | 3rd Oct 24    | TBD           |
@tusharchou What is the new delivery date for 0.1.1

2024-10-07 10:21 UTC, merged