Readme Update
tusharchou/local-data-platform pull request #41
Opened 2024-10-10 22:09 UTC by redpheonixx

Added data pipeline overview.

2024-10-11 03:53 UTC, tusharchou commented
Hi @redpheonixx thank you so much for taking the effort to contribute directly to the core documentation of this project. We could use some help documenting orchestration too. Let's me know on comments whatever issues come to your mind. Happy Friday!

2024-10-15 12:01 UTC, mrutunjay-kinagi approved these changes
LGTM ! Thank you for contributing.

2024-10-16 15:52 UTC, tusharchou requested changes

2024-10-16 19:03 UTC, redpheonixx commented
Made changes in overall readme structure and also removed some areas which seemed unnecessary to me. @tusharchou @mrutunjay-kinagi @abhishekkar0603  please review and add comments.

2024-10-16 19:11 UTC, tusharchou approved these changes

2024-10-18 16:01 UTC, merged