boiler plate code for dbt transformation
tusharchou/local-data-platform pull request #55
Opened 2024-10-25 18:29 UTC by redpheonixx

---
name: Boiler Plate Code for DBT transformations
about: using medallion architecture writing down bronze layer, silver layer, and gold layer transformation using iceberg rest catalog.
title: Boiler Plate code for DBT transformation
labels: Transformation layer
assignees: Amit Singh

---

#45 

wrote dbt transformation layer as per medallion architecture 
 
dbt's low learning curve and SQL-based workflow empower data teams without advanced programming knowledge to build and maintain transformations. This makes it a better fit for companies looking for agility and simplicity in data pipelines.

2024-10-28 16:33 UTC, tusharchou commented on local-data-platform/local_data_platform/makefile
@redpheonixx what issue is this associated with?

2024-10-28 16:34 UTC, redpheonixx commented on local-data-platform/local_data_platform/makefile
#57 
following below blog for makefile 
https://motherduck.com/blog/duckdb-python-e2e-data-engineering-project-part-1/

2024-11-08 07:47 UTC, tusharchou commented
Raising a pull request (PR) from a fork's main branch to a repository's main branch is generally discouraged for several reasons:

1. **Complexity and Confusion**: Using the main branch of your fork for PRs can create confusion if you make other changes or updates to your fork's main branch. It becomes harder to track what specific changes the PR is addressing.

2. **Continuous Integration Issues**: Many projects have automated checks and continuous integration (CI) workflows that run on branches. If you use the main branch for PRs, these workflows might get triggered unnecessarily, potentially causing conflicts or errors.

3. **Maintenance Difficulty**: It's easier to maintain a clean and organized history if you create a separate feature branch for each set of changes. This approach avoids cluttering the main branch and makes it simpler to manage and merge changes.

4. **Conflict Management**: Keeping changes in isolated branches helps in managing conflicts better. If your main branch is used for a PR and it diverges significantly from the upstream main branch, resolving conflicts can become more complicated.

5. **Best Practices**: Following best practices, like creating feature branches for specific changes or issues, improves collaboration and code quality. It also aligns with how most open-source projects and development teams operate.

### Best Practice Workflow:
1. **Create a Feature Branch**:
   ```sh
   git checkout -b feature/your-feature-name
   ```

2. **Make Your Changes and Commit**:
   ```sh
   git commit -m "Describe your changes"
   ```

3. **Push Your Feature Branch to Your Fork**:
   ```sh
   git push origin feature/your-feature-name
   ```

4. **Open a PR from Your Feature Branch to the Upstream Main Branch**:
   - Go to the repository on GitHub.
   - Open a PR from `your-fork:feature/your-feature-name` to `upstream:main`.

This approach keeps your development process clean and organized. It ensures that the main branches remain stable and only contain code that is ready for production.

Feel free to ask if you need more details or help with Git workflows! 🚀✨

2024-11-11 16:44 UTC, rakhioza07 requested changes
Please fix review comments and move into draft PR until changes are made.

Great work on exception handling and clean coding efforts!

2024-11-11 16:44 UTC, rakhioza07 commented on local-data-platform/dist/local_data_platform-0.1.0.tar.gz
Please don't add tar.gz, whl or heavy source files as a part of code commits

Only consider code, sample data and config file, scripts for PRs

2024-11-11 16:44 UTC, rakhioza07 commented on local-data-platform/local_data_platform/transformations/dbt_models/bronze/bronze.sql
Consider moving all SQL files to a central place

Consider keeping code, data, queries, configs in seperate directory structures

2024-11-11 16:44 UTC, rakhioza07 commented on local-data-platform/local_data_platform/transformations/silver_layer.py
This script needs to be OOP

2024-11-11 16:44 UTC, rakhioza07 commented on local-data-platform/poetry.lock
Does this file need to be a part of the commit? If no, please mention in gitignore

2024-11-11 16:44 UTC, rakhioza07 commented on local-data-platform/real_world_use_cases/near_data_lake/tmp.py
> +p_path="file:///"+str(p)
Use f-strings for string manipulation

2025-08-02 18:27 UTC, tusharchou commented on .github/workflows/manual.yml
> +# This is a basic workflow that is manually triggered
please take a pull from main to sync with the latest changes @redpheonixx sorry for the late review

2025-08-02 18:27 UTC, tusharchou commented on .gitignore
pull changes please

2025-08-02 18:28 UTC, tusharchou commented on local-data-platform/README.md
<img width="681" height="651" alt="Screenshot 2025-08-02 at 11 58 17 PM" src="https://github.com/user-attachments/assets/174f783e-9050-4ff4-a540-6acb17f0221e" />
Please update proper documentation as discussed on call

2025-08-02 18:29 UTC, tusharchou commented on local-data-platform/dist/local_data_platform-0.1.0.tar.gz
@redpheonixx please respond , thank you @rakhioza07

2025-08-02 18:30 UTC, tusharchou commented on local-data-platform/local_data_platform/makefile
@redpheonixx what happened to this?

2025-08-02 18:30 UTC, tusharchou commented on local-data-platform/local_data_platform/transformations/dbt_models/bronze/bronze.sql
great idea @rakhioza07 , @redpheonixx look up dbt package

2025-08-02 18:31 UTC, tusharchou commented on local-data-platform/local_data_platform/transformations/silver_layer.py
great idea @rakhioza07 , i will pick it up in next PR

2025-08-02 18:31 UTC, tusharchou commented on local-data-platform/poetry.lock
I think it does @redpheonixx please confirm

2025-08-02 18:32 UTC, tusharchou commented on local-data-platform/pyproject.toml
seems wrong we did it

2025-08-02 18:33 UTC, tusharchou approved these changes
Thank you. for everything @redpheonixx You have been a core contributor and I wish you all the best in your career! 🚀

2025-08-02 18:40 UTC, rakhioza07 approved these changes
Unseen/unreviewed changes, approving as directed by @tusharchou . Please rollback in case of failed deployment.

2025-08-04 10:53 UTC, mrutunjay-kinagi commented
@redpheonixx, Please resolve conflicts and update the PR.

cc @tusharchou

2025-09-13 08:01 UTC, closed without merging