V0.1.1 : pytest for BigQueryToCSV.extract()
tusharchou/local-data-platform pull request #83
Opened 2024-11-04 14:49 UTC by tusharchou

---
name: Pull request
about: Implement an solution for this project
title: ''
labels: ''
assignees: ''

---

**Is your pull request related to a issue? Please tag.**

**Describe the solution you have implemented**

**Describe why alternatives you considered are not optimal**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the pull request here.

2024-11-04 14:56 UTC, rakhioza07 requested changes

2024-11-05 13:01 UTC, mrutunjay-kinagi commented
Please Add Test case for the following functionalities : 
1. BigQuery.get()
2. BigQuery.put()
3. CSV.get()
4. CSV.put()
5. Iceberg.get()
6. Iceberg.put()
7. Parquet.get()
8. Parquet.put()

2024-11-20 11:33 UTC, tusharchou commented on local-data-platform/tests/test_metadata.py
> +    stats = table_statistics_from_iceberg_metadata(
#1 I am trying to solve for the statistics here @rakhioza07 @redpheonixx

2024-11-23 06:13 UTC, tusharchou commented on local-data-platform/tests/test_dimension.py
> +def test_get():
Love how simple this is 🥇

2025-07-27 10:34 UTC, tusharchou commented
I will work on this

2025-12-21 13:16 UTC, closed without merging